#!/usr/bin/env bash

# Exit on any error
set -e

print_logo

# Source utility functions
source utils

file_exists "packages.conf" || exit 1
file_exists "dotfiles.conf" || exit 1
file_exists "services.conf" || exit 1

source packages.conf
source dotfiles.conf
source services.conf

# Update the system first
log_info "Updating system..."
sudo apt update && sudo apt upgrade -y

log_info "Installing system utilities..."
install_apt_packages "${APT_PACKAGES[@]}"

log_info "Installing other packages..."
install_starship_prompt
install_lazydocker
setup_tmux
install_vim_pluginmanager
install_fzf
install_navi
install_nvim
install_ripgrep

enable_services "${SERVICES[@]}"

setup_dotfiles
stow_dotfiles "${DOTFILES_TO_STOW[@]}"

# Install Vim plugins after stowing dotfiles
install_vim_plugins

log_info "Setup complete! You may want to reboot your system."
